/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeTestRouteImport } from './routes/theme-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTagsRouteImport } from './routes/settings/tags'
import { Route as PassagePassageIdRouteImport } from './routes/passage/$passageId'

const ThemeTestRoute = ThemeTestRouteImport.update({
  id: '/theme-test',
  path: '/theme-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagePassageIdRoute = PassagePassageIdRouteImport.update({
  id: '/passage/$passageId',
  path: '/passage/$passageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/theme-test': typeof ThemeTestRoute
  '/passage/$passageId': typeof PassagePassageIdRoute
  '/settings/tags': typeof SettingsTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/theme-test': typeof ThemeTestRoute
  '/passage/$passageId': typeof PassagePassageIdRoute
  '/settings/tags': typeof SettingsTagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/theme-test': typeof ThemeTestRoute
  '/passage/$passageId': typeof PassagePassageIdRoute
  '/settings/tags': typeof SettingsTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/theme-test'
    | '/passage/$passageId'
    | '/settings/tags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/theme-test' | '/passage/$passageId' | '/settings/tags'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/theme-test'
    | '/passage/$passageId'
    | '/settings/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ThemeTestRoute: typeof ThemeTestRoute
  PassagePassageIdRoute: typeof PassagePassageIdRoute
  SettingsTagsRoute: typeof SettingsTagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-test': {
      id: '/theme-test'
      path: '/theme-test'
      fullPath: '/theme-test'
      preLoaderRoute: typeof ThemeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passage/$passageId': {
      id: '/passage/$passageId'
      path: '/passage/$passageId'
      fullPath: '/passage/$passageId'
      preLoaderRoute: typeof PassagePassageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ThemeTestRoute: ThemeTestRoute,
  PassagePassageIdRoute: PassagePassageIdRoute,
  SettingsTagsRoute: SettingsTagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
